services:
  - type: web
    name: swipe-rent-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RAPID_API_KEY
        sync: false
      - key: RAPID_API_HOST
        sync: false
      - key: FRONTEND_URL
        sync: false 